#region Validate you have the needed files
$pem = 'testcert.techsnips.io.pem'# public certificate generated by your CA
$intermediate = 'intermediate.pem'# CA's public intermediate certificate
$pkcs12 = 'testcert.techsnips.io.pfx' # You new chained pkcs12 certificate
$privateKey = 'testcert.techsnips.io.key' # private key created when CSR was made

$certDir = 'C:\certs'
Get-ChildItem $certDir
#endregion 

#region validate input certs
# View and verify your public certificate
ise $pem 
openssl x509 -out peminfo.txt -text -in $pem
ise .\peminfo.txt
Remove-Item .\peminfo.txt

# View and verify your CA's public intermediate certificate
openssl x509 -out intermediateInfo.txt -text -in $intermediate
ise .\intermediateInfo.txt
Remove-Item .\intermediateInfo.txt
#endregion validate input certs

#region Create and validate PKCS12
# Create PKCS using private key, intermediated, and public certificate
$pkcsArgs = "pkcs12 -export -out $pkcs12 -inkey $privateKey -in $pem -certfile $intermediate"
Start-Process openssl $pkcsArgs # You will be prompted  to enter an export password

#verify the certificate
get-content $pkcs12

$verifyArgs = "pkcs12 -info -in $pkcs12 -out pfxInto.txt" 
Start-Process openssl $verifyArgs

ise .\pfxInto.txt
rm .\pfxInto.txt
#endregion Create and validate PKCS12